### ISSUE TITLE
curl_multi_select 5.3+

### ISSUE THREAD

**Issue by zckernel** [jmathai/php-multi-curl#14] opened 2013-11-21 15:57 UTC
Its hapens that on my PHP 5.3.27 I got an infinite loop because curl_multi_select($this->mc)
always return -1.

I have changed the correspond block to:
<code>
while($this->running && ($this->execStatus == CURLM_OK 
    || $this->execStatus == CURLM_CALL_MULTI_PERFORM))
      {
        usleep($outerSleepInt);
        $outerSleepInt *= $this->sleepIncrement;
        if(curl_multi_select($this->mc) == -1)
            usleep(100); 
        
        do{
          $this->execStatus = curl_multi_exec($this->mc, $this->running);
          usleep($innerSleepInt);
          $innerSleepInt *= $this->sleepIncrement;
        }while($this->execStatus==CURLM_CALL_MULTI_PERFORM);
        $innerSleepInt = 1;
        
        $this->storeResponses();
</code>

**Comment by jmathai** [comment] 2015-10-19 17:23
I believe this is a duplicate of gh-9. Closing this in favor of that. I'm using this in another project on 5.3+ and will be updating this library. Will check if that solves this issue.

**Closed by jmathai** 2015-10-19 17:23 UTC
